const connect = require("./connect.js");
const express = require("express");
const cors = require("cors");
const users = require("./routes/userRoutes.js");
const app = express(); 
const port = 3000;
const axios=require("axios");
require('dotenv').config();

app.use(cors());
app.use(express.json());

app.get("/", (req, res) => {
  res.send("GraminAI backend is working ✅");
});
app.use(users);

app.post('/chat', async (req, res) => {
  const userPrompt = req.body.prompt;

  try {
    const response = await axios.post(
       `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
      {
        contents: [{ parts: [{ text: userPrompt }] }]
      }
    );

    console.log("Full Gemini API response:", JSON.stringify(response.data, null, 2));

    const reply = response.data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!reply) {
      return res.status(500).json({ error: "No reply generated by Gemini." });
    }

    res.json({ reply });
  } catch (error) {
    console.error("Gemini API error:", error?.response?.data || error.message);
    res.status(500).json({ error: 'Error generating response from Gemini' });
  }
});


app.listen(port, ()=>{
    console.log(`Server is running on port ${port}`);
    connect.connectToServer();
    console.log("Connected to MongoDB");
});